### ISSUE TITLE
New page at the beginning of each chapter

### ISSUE THREAD

**Issue by mrnajjari** [skulumani/thesis-gwu#25]
Hi Shankar,

I know the library accepted this thesis. "Development of a High-order Navier-Stokes Solver using Flux Reconstruction to Simulate Three-dimensional Vortex Structures in a Curved Artery Model".
So it would be much nice looking if you can add this style where at the begining of each chapter we have a page only showing chapter # and name like below.
![image](https://user-images.githubusercontent.com/29776402/40319843-982eb13a-5cf7-11e8-96fe-aa4800bc7ec8.png)

**Comment by skulumani** [comment]
That's awesome. I'll work on adding an option `reza-title` to do something like this.

**Comment by skulumani** [comment]
This isn't in the standard set by GWU but I'll try to add it this weekend.

**Comment by mrnajjari** [comment]
Hi,
Thanks.
Oh, I did it with following commands after the last package:

\titleformat{\chapter}[display]
{\bfseries\huge}{\huge\chaptertitlename\ \thechapter}{24pt}{\filright}
\titlespacing*{\chapter}
{0pt}{48pt}{0pt}

After this put "\newpage" at the beginning of each chapter.
